version: "1"

services:
  db:
    build: ./db
    container_name: xls-db
    volumes:
      - db-data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  app:
    build:
      context: .
      dockerfile: ./LearnSecurity/Dockerfile
    env_file: ./.env
    volumes:
      - ./practice:/opt/xls/practice
      - ./lesson:/opt/xls/lesson
    ports:
      - "80:8080"

  manager-app:
    build:
      context: .
      dockerfile: ./LearnSecurityManager/Dockerfile
    env_file: ./.env
    volumes:
      - ./practice:/opt/xls/practice
      - ./lesson:/opt/xls/lesson
    ports:
      - "8080:8080"

volumes:
  db-data-volume:
    name: xls-db
