version: ‘3’

services:
  mysql:
    build: ./mysql
    volumes:
      - db-data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sqlInjection
      - MYSQL_USER=sqlInjection
      - MYSQL_PASSWORD=sqlInjection
    container_name: SqlInjection-Mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8081:80"
    container_name: SqlInjection-phpmyadmin

  php-apache:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql
    container_name: SqlInjection-php

volumes:
  db-data-volume:
    name: SqlInjection-db
